export const PROM_METRICS = {
    AGGREGATOR_MESSAGES_COUNT: 'PROM_METRIC_AGGREGATOR_MESSAGES_COUNT',
    INSTANCES_COUNT: 'PROM_METRIC_INSTANCES_GAUGE',
    ZONE_MESSAGE_COUNT: 'PROM_METRIC_ZONE_MESSAGE_COUNT',
};

export const METRICS_NAMES = {
    AGGREGATOR_MESSAGES_COUNT: 'aggregator_messages_count',
    INSTANCES_COUNT: 'instances_gauge',
    ZONE_MESSAGE_COUNT: 'zone_message_count',
};
