export const PROM_METRICS = {
    AGGREGATOR_MESSAGES_SUCCESS: 'PROM_METRIC_AGGREGATOR_MESSAGES_SUCCESS',
    AGGREGATOR_MESSAGES_RETRY: 'PROM_METRIC_AGGREGATOR_MESSAGES_RETRY',
    AGGREGATOR_MESSAGES_FAIL: 'PROM_METRIC_AGGREGATOR_MESSAGES_FAIL',
};

export const METRICS_NAMES = {
    AGGREGATOR_MESSAGES_SUCCESS: 'aggregator_messages_success',
    AGGREGATOR_MESSAGES_RETRY: 'aggregator_messages_retry',
    AGGREGATOR_MESSAGES_FAIL: 'aggregator_messages_fail',
};
