version: "3.9"
services:
  aggregator-pc:
    image: ps2alerts/aggregator:dev
    restart: "no"
    volumes:
      - "../../:/app:rw"
    ports:
      - "1337"
      - "9229:9229"
    networks:
      - "ps2alerts"
    environment:
      CENSUS_ENVIRONMENT: "ps2"
    labels:
      traefik.enable: "false"

  aggregator-ps4eu:
    image: ps2alerts/aggregator:dev
    restart: "no"
    volumes:
      - "../../:/app:rw"
    ports:
      - "1338"
    networks:
      - "ps2alerts"
    environment:
      CENSUS_ENVIRONMENT: "ps2ps4eu"
    labels:
      traefik.enable: "false"

  aggregator-ps4us:
    image: ps2alerts/aggregator:dev
    restart: "no"
    volumes:
      - "../../:/app:rw"
    ports:
      - "1339"
    networks:
      - "ps2alerts"
    environment:
      CENSUS_ENVIRONMENT: "ps2ps4us"
    labels:
      traefik.enable: "false"
networks:
  ps2alerts:
    external:
      name: ps2alerts
