version: "3.9"
services:
  aggregator-pc:
    image: ps2alerts/aggregator:dev
    restart: "no"
    volumes:
      - "../../:/app:rw"
    ports:
      - "1337"
      - "9229:9229"
    networks:
      - "ps2alerts"
    environment:
      NODE_ENV: "development"
      VERSION: "12345"
      CENSUS_ENVIRONMENT: "ps2"
      CENSUS_SERVICE_ID: "$CENSUS_SERVICE_ID"
      REDIS_HOST: "ps2alerts-redis"
      REDIS_DB: "0"
      INTERNAL_API_HOST: "http://ps2alerts-api:3000"
      INTERNAL_API_USER: "ps2alerts"
      INTERNAL_API_PASS: "foobar"
      LOGGER_TRANSPORTS: "console"
    labels:
      traefik.enable: "false"

  aggregator-ps4eu:
    image: ps2alerts/aggregator:dev
    restart: "no"
    volumes:
      - "../../:/app:rw"
    ports:
      - "1338"
    networks:
      - "ps2alerts"
    environment:
      NODE_ENV: "development"
      VERSION: "12345"
      CENSUS_ENVIRONMENT: "ps2ps4eu"
      CENSUS_SERVICE_ID: "$CENSUS_SERVICE_ID"
      REDIS_HOST: "ps2alerts-redis"
      REDIS_DB: "0"
      LOGGER_TRANSPORTS: "console"
      INTERNAL_API_HOST: "http://ps2alerts-api:3000"
      INTERNAL_API_USER: "ps2alerts"
      INTERNAL_API_PASS: "foobar"
    labels:
      traefik.enable: "false"

  aggregator-ps4us:
    image: ps2alerts/aggregator:dev
    restart: "no"
    volumes:
      - "../../:/app:rw"
    ports:
      - "1339"
    networks:
      - "ps2alerts"
    environment:
      NODE_ENV: "development"
      VERSION: "12345"
      CENSUS_ENVIRONMENT: "ps2ps4us"
      CENSUS_SERVICE_ID: "$CENSUS_SERVICE_ID"
      REDIS_HOST: "ps2alerts-redis"
      REDIS_DB: "0"
      LOGGER_TRANSPORTS: "console"
      INTERNAL_API_HOST: "http://ps2alerts-api:3000"
      INTERNAL_API_USER: "ps2alerts"
      INTERNAL_API_PASS: "foobar"
    labels:
      traefik.enable: "false"
networks:
  ps2alerts:
    external:
      name: ps2alerts
