---
- hosts: localhost
  vars:
    root_dir: "{{ playbook_dir }}/../../"
    debug: "false"
  tasks:
    - debug:
        msg: "========= 📡 Starting Aggregator Module - MULTI ENVIRONMENT MODE 📡 ========="

    - name: Delete dist folder
      file:
        path: "{{ root_dir }}/dist"
        state: absent

    - name: Stop any running aggregator modules
      register: output
      docker_compose:
        project_src: .
        files:
          - docker-compose.yml
        state: absent

    - name: Start up aggregator modules
      register: output
      docker_compose:
        project_src: .
        files:
          - docker-compose.yml
        state: present
