---
- hosts: localhost
  vars:
    root_dir: "{{ playbook_dir }}/../../"
  vars_files:
    - ../../vars.local.yml
  tasks:
    - name: Start Websocket Dev Image
      docker_container:
        name: ps2alerts-websocket
        image: ps2alerts/websocket:dev
        state: started
        restart: no
        recreate: yes
        restart_policy: "no"
        volumes:
          - "{{ root_dir | realpath }}/app:/app:rw"
        ports:
          - "1337"
        networks:
          - name: "ps2alerts"
        tty: true
        env:
          NODE_ENV: "development"
          VERSION: "12345"
          DB_USER: "root"
          DB_PASS: "foobar"
          DB_HOST: "ps2alerts-db"
          DB_PORT: "27017"
          DB_SCHEMA: "ps2alerts"
          DB_DEBUG: "true"
          REDIS_ENABLED: "1"
          REDIS_HOST: "ps2alerts-redis"
          REDIS_DB: "1"
          API_BASE_URL: "http://api.dev.ps2alerts.com"
          CENSUS_SERVICE_ID: "{{ census_service_id }}"
          LOGGER_DISCORD_WEBHOOK: "https://discordapp.com/api/webhooks/736389415936720917/RkeDsvhGFjq3HSewPU_q59Et-6cHKCdkISw7apatWF8mJFc0w48YH88-_pG9hh03ljJ6"
        labels:
          traefik.enable: "true"
          traefik.http.routers.ps2alerts-websocket.rule: "Host(`wss.dev.ps2alerts.com`)"
#          traefik.http.routers.ps2alerts-websocket.tls: "true"
#          traefik.http.routers.ps2alerts-websocket.tls.domains[0].main: "wss.dev.ps2alerts.com"
