---
- hosts: localhost
  vars:
    root_dir: "{{ playbook_dir }}/../../"
    debug: "false"
  vars_files:
    - ../../vars.local.yml
  tasks:
    - debug:
        msg: "========= 📡 Starting Aggregator Module 📡  ========="

    - name: Delete dist folder
      file:
        path: "{{ root_dir }}/dist"
        state: absent

    - name: Start Aggregator Dev Image
      docker_container:
        name: ps2alerts-aggregator
        image: ps2alerts/aggregator:dev
        state: present
        restart: no
        recreate: yes
        restart_policy: "no"
        volumes:
          - "{{ root_dir | realpath }}:/app:rw"
        ports:
          - "1337"
          - "9229:9229"
        networks:
          - name: "ps2alerts"
        tty: true
        env:
          NODE_ENV: "development"
          VERSION: "12345"
          DB_USER: "root"
          DB_PASS: "foobar"
          DB_HOST: "ps2alerts-db"
          DB_PORT: "27017"
          DB_SCHEMA: "ps2alerts"
          DB_DEBUG: "false"
          REDIS_HOST: "ps2alerts-redis"
          REDIS_DB: "0"
          API_BASE_URL: "http://dev.api.ps2alerts.com"
          CENSUS_SERVICE_ID: "{{ census_service_id }}"
          LOGGER_TRANSPORTS: "console"
          NODE_DEBUG: "{{ debug }}"
        labels:
          traefik.enable: "false"
