---
- hosts: localhost
  vars:
    root_dir: "{{ playbook_dir }}/../../"
    debug: "false"
  tasks:
    - debug:
        msg: "========= 📡 Starting Aggregator Module - PC ONLY 📡 ========="

    - name: Delete dist folder
      file:
        path: "{{ root_dir }}/dist"
        state: absent

    - name: Stop aggregator if running
      docker_container:
        name: ps2alerts-aggregator-pc
        state: absent

    - name: Start Aggregator Dev Image (ps2 PC ONLY)
      docker_container:
        name: ps2alerts-aggregator-pc
        image: ps2alerts/aggregator:dev
        state: started
        restart: no
        recreate: yes
        restart_policy: "no"
        volumes:
          - "{{ root_dir }}:/app:rw"
        ports:
          - "1337"
          - "9229:9229"
        networks:
          - name: "ps2alerts"
        tty: true
        labels:
          traefik.enable: "false"
