export enum MetagameEventIds {
    MELTDOWN_ESAMIR = 186,
    MELTDOWN_HOSSIN = 187,
    MELTDOWN_AMERISH = 188,
    MELTDOWN_INDAR = 189,
    MELTDOWN_UNSTABLE_ESAMIR = 190,
    MELTDOWN_UNSTABLE_HOSSIN = 191,
    MELTDOWN_UNSTABLE_AMERISH = 192,
    MELTDOWN_UNSTABLE_INDAR = 193
}
