---
# This playbook handles publishing a AdminAggregator control message.

- hosts: localhost
  vars:
    queue_name: "adminAggregator-development"
    environment: ""
    hostname: "localhost"
    user: "user"
    password: "bitnami"
    vhost: "%2F"
    world: ""
    zone: ""
    valid_worlds: ["1", "10", "13", "17", "19", "40", "1000", "2000"]
    valid_zones: ["2", "4", "6", "8"]
    valid_factions: ["1", "2", "3"]
  vars_prompt:
    - name: type
      prompt: "Select message type [start, end, activeInstances]"
      private: no
      default: "start"

    - name: world
      prompt: "[start] Select world {{ valid_worlds }}"
      private: no
      default: 19

    - name: zone
      prompt: "[start] Select zone {{ valid_zones }} "
      private: no
      default: 2

    - name: faction
      prompt: "[start] Select triggering faction {{ valid_factions }} "
      private: no
      default: 1

    - name: meltdown
      prompt: "[start] Meltdown? [true/false]"
      private: no
      default: false

    - name: duration
      prompt: "[start] Specify duration in seconds. Default is \"5400\" for 1:30 hours"
      private: no
      default: 5400

    - name: instanceId
      prompt: "[end] Specify PS2Alerts Instance ID to end"
      private: no

    - name: env
      prompt: "Select environment to send message to [dev, staging, production]"
      private: no
      default: "dev"
  tasks:
    - name: Ensure world is valid if start type
      fail:
        msg: "World isn't valid!"
      when: type == "start" and world not in valid_worlds

    - name: Ensure zone is valid if start type
      fail:
        msg: "Zone isn't valid!"
      when: type == "start" and zone is not in valid_zones

    - name: Ensure faction is valid if start type
      fail:
        msg: "Zone isn't valid!"
      when: type == "start" and faction is not in valid_factions

    - name: Create start message body
      set_fact:
        message:
          type: "{{ type }}"
          body:
            instanceId: "{{ 100000 | random }}"
            world: "{{ world }}"
            zone: "{{ zone }}"
            faction: "{{ faction }}"
            meltdown: "{{ meltdown }}"
            type: "metagame"
            start: "{{ ansible_date_time.epoch }}"
            duration: "{{ duration }}"
      when: type == "start"

    - name: Create end message body
      set_fact:
        message:
          type: "{{ type }}"
          body:
            instanceId: "{{ instanceId }}"
      when: type == "end"

    - name: Create activeInstances message body
      set_fact:
        message:
          type: "{{ type }}"
          body:
            foo: "bar"
      when: type == "activeInstances"

    - name: Set hostname if staging or production, set correct hostname and password
      set_fact:
        hostname: "rabbit.ps2alerts.com"
        user: "{{ rabbit.user }}"
        password: "{{ rabbit.password }}"
        queue_name: "adminAggregator-{{ env }}"
        vhost: "ps2alerts"
      when: env == "staging" or env == "production"

    - debug:
        msg: "Sending message to: {{ user }}:{{ password }}@{{ hostname }}{{ vhost }} - {{ queue_name }}"

    - debug:
        msg: "{{ message }}"

    - name: Publish Instance message
      rabbitmq_publish:
        queue: "{{ queue_name }}"
        body: "{{ message | to_json }}"
        proto: amqp
        host: "{{ hostname }}"
        port: 5672
        username: "{{ user }}"
        password: "{{ password }}"
        vhost: "{{ vhost }}"
        durable: true
